[build]
  command = "bundle exec jekyll build"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.4.0"
  JEKYLL_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[build.processing]
  skip_processing = false 